### ISSUE TITLE
Failure to deserialize response with reformatted address

### ISSUE THREAD

**Issue by MrMallon** [Autoaddress-AA2/autoaddress2.0-sdk-net#1]
When making a request to ReverseGeocode using a addressProfileName attribute in the request object, the response fails to deserialize into the response object. 

After debugging the the autoaddress2.0-sdk-net project I found it was failing at the point of deserializeing the json ReformattedAddressResult:

JsonConvert.DeserializeObject<Model.ReverseGeocode.Response>(result);

I have implemented a fix in my project where I use a class instead of an enum and it works as expected.

The Class:

`namespace Autoaddress.Autoaddress2_0.Model
{
    /// <summary>
    /// Reformatted Address Result
    /// </summary>
    public class ReformattedAddressStatus
    {
        public int code { get; set; }

        public string Text { get; set; }
    }
}`

Implemented in Hit Class: 

`namespace Autoaddress.Autoaddress2_0.Model.ReverseGeocode
{
    /// <summary>
    /// Hit returned in a ReverseGeocode Response object
    /// </summary>
    public class Hit
    {
        [JsonConstructor]
        internal Hit(int addressId, string[] postalAddress, string[] geographicAddress, string[] vanityAddress, ReformattedAddressStatus reformattedAddressResult, string[] reformattedAddress, double distance, Model.Link[] links)
        {
            if (postalAddress == null || postalAddress.Length == 0) throw new ArgumentNullException("postalAddress");
            if (distance < -0.00001D) throw new ArgumentNullException("distance");
            if (links == null) throw new ArgumentNullException("links");

            AddressId = addressId;
            PostalAddress = postalAddress;
            GeographicAddress = geographicAddress;
            VanityAddress = vanityAddress;
            ReformattedAddressResult = reformattedAddressResult != null?reformattedAddressResult: new ReformattedAddressStatus() { code = 0, Text = "Unknown"};
            ReformattedAddress = reformattedAddress;
            Distance = distance;

            var newLinks = new List<Model.Link>();

            foreach (Model.Link link in links)
            {
                Model.Link newLink;

                switch (link.Rel)
                {
                    case "getEcadData":
                        newLink = new GetEcadData.Link(link.Rel, link.Href);
                        break;
                    default:
                        newLink = link;
                        break;
                }

                newLinks.Add(newLink);
            }

            Links = newLinks.ToArray();
        }

        /// <summary>
        /// Gets the Address ID (i.e. ECAD ID for Ireland).
        /// </summary>
        public int AddressId { get; private set; }

        /// <summary>
        /// Gets the postal address for the building in requested language.
        /// </summary>
        public string[] PostalAddress { get; private set; }

        /// <summary>
        /// Gets the geographic address for the building in requested language.
        /// </summary>
        public string[] GeographicAddress { get; private set; }

        /// <summary>
        /// Gets the vanity address (if requested).
        /// </summary>
        public string[] VanityAddress { get; private set; }

        /// <summary>
        /// Gets the reformatted address result.
        /// </summary>
        public ReformattedAddressStatus ReformattedAddressResult { get; private set; }

        /// <summary>
        /// Gets the address reformatted (if an address profile name supplied in request).
        /// </summary>
        public string[] ReformattedAddress { get; private set; }

        /// <summary>
        /// Get the distance of building from location in metres.
        /// </summary>
        public double Distance { get; private set; }

        /// <summary>
        /// Gets the links.
        /// </summary>
        public Model.Link[] Links { get; private set; }
    }
}`

**Comment by alanmartin0** [comment]
Fixed in v1.0.9.
Thanks for reporting the issue.
