### ISSUE TITLE
AutoComplete Has no Reformatted Address Option

### ISSUE THREAD

**Issue by MrMallon** [Autoaddress-AA2/autoaddress2.0-sdk-net#2]
Should the autoAddressClient's  Autocomplete return a reformatted address similar to the ReverseGeocode and FindAddressAsync ?

**Comment by alanmartin0** [comment]
No, AutoComplete is for returning options only.
To retrieve a ReformattedAddress for an option, you must call FindAddress with the corresponding Link object.
See AutoCompleteAsyncThenFindAddressAsync_IE_D08XY00_ReturnsValidResponse in the SDK tests for an example of calling FindAddress with an option Link object.
