### ISSUE TITLE
FindAddressAsync returns inaccessible options  

### ISSUE THREAD

**Issue by MrMallon** [Autoaddress-AA2/autoaddress2.0-sdk-net#3]
Searching "Grafton street, Dublin 2" returns 188 TotalOptions using FindAddressAsync.
However the Options property is not populated, when checking this during debugging the Options says: "Could not evaluate Children"

On the website "Grafton street, Dublin 2" returns various options that lead to more options. 

Using FindAddressAsync works as expected when searching "Grafton street, Cork".  TotalOptions are 5 and the 5 Options are accessible.

**Comment by MrMallon** [comment]
Hi I was wondering if there has been any progression with this? I can try supply more information if required ?

**Comment by alanmartin0** [comment]
You are using the wrong limit. Please use limit = -1.

**Comment by MrMallon** [comment]
@alanmartin0  works like a charm! Thanks for getting back to me.
